#Final Project - Data Gathering and Warehousing - DSSA-5102#
Instructor: Melissa Laurino
Spring 2025

##Data Cleaning##
Let's load our data, clean it up and prepare it for use in our final project.

In [2]:
# Load necessary packages:
import pandas as pd
import numpy as np
import os

In [3]:
# load AKC csv file
akc_dogs_df = pd.read_csv('datasets/akc-data-latest.csv')
# load Pet Owners file
pet_owners_df = pd.read_csv('datasets/pet-owners.csv')

# Breed Dataset

Let's clean up the breed dataset

In [4]:
# rename the first column to breed
akc_dogs_df.columns.values[0] = "breed"
akc_dogs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   breed                        277 non-null    object
 1   description                  277 non-null    object
 2   temperament                  276 non-null    object
 3   popularity                   198 non-null    object
 4   min_height                   277 non-null    float64
 5   max_height                   277 non-null    float64
 6   min_weight                   275 non-null    float64
 7   max_weight                   275 non-null    float64
 8   min_expectancy               274 non-null    float64
 9   max_expectancy               274 non-null    float64
 10  group                        277 non-null    object
 11  grooming_frequency_value     270 non-null    float64
 12  grooming_frequency_category  270 non-null    object
 13  shedding_value               257 non-null    float64
 14  shedding_category            257 non-null    object
 15  energy_level_value           271 non-null    float64
 16  energy_level_category        271 non-null    object
 17  trainability_value           253 non-null    float64
 18  trainability_category        253 non-null    object
 19  demeanor_value               252 non-null    float64
 20  demeanor_category            252 non-null    object
dtypes: float64(11), object(10)
memory usage: 45.6+ KB

In [5]:
# Drop the columns we will not be using
akc_dogs_df = akc_dogs_df.drop(columns=['description', 'group', 'grooming_frequency_value', 'grooming_frequency_category', 'shedding_value', 'shedding_category'])

In [6]:
# Preview our dataframe after the column drops
akc_dogs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 277 entries, 0 to 276
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   breed                  277 non-null    object
 1   temperament            276 non-null    object
 2   popularity             198 non-null    object
 3   min_height             277 non-null    float64
 4   max_height             277 non-null    float64
 5   min_weight             275 non-null    float64
 6   max_weight             275 non-null    float64
 7   min_expectancy         274 non-null    float64
 8   max_expectancy         274 non-null    float64
 9   energy_level_value     271 non-null    float64
 10  energy_level_category  271 non-null    object
 11  trainability_value     253 non-null    float64
 12  trainability_category  253 non-null    object
 13  demeanor_value         252 non-null    float64
 14  demeanor_category      252 non-null    object
dtypes: float64(9), object(6)
memory usage: 32.6+ KB

In [7]:
# let's look for any rows with missing values
rows_with_missing_values = akc_dogs_df[akc_dogs_df.isna().any(axis=1)]
print(rows_with_missing_values)

                         breed                           temperament  \
5             American Bulldog                 Loyal, Self-Confident
9    American Hairless Terrier             Energetic, Alert, Curious
10      American Leopard Hound      Sociable, Energetic, Intelligent
14      Appenzeller Sennenhund              Agile, Versatile, Lively
16           Australian Kelpie             Loyal, Alert, Intelligent
..                         ...                                   ...
260        Transylvanian Hound  Courageous, Good-Natured, Determined
261  Treeing Tennessee Brindle          Friendly, Alert, Intelligent
268                 Wetterhoun      Loyal, Good-Natured, Intelligent
273             Working Kelpie             Alert, Eager, Intelligent
275             Yakutian Laika     Affectionate, Intelligent, Active

    popularity  min_height  max_height  min_weight  max_weight  \
5          NaN       50.80       63.50   27.215542   45.359237
9          136       30.48       40.64    5.443108    7.257478
10         NaN       53.34       68.58   20.411657   31.751466
14         NaN       48.26       55.88   21.772434   31.751466
16         NaN       43.18       50.80         NaN         NaN
..         ...         ...         ...         ...         ...
260        NaN       55.88       66.04   24.947580   24.947580
261        NaN       40.64       60.96   13.607771   22.679619
268        NaN       12.70       58.42   22.679619   34.019428
273        NaN       48.26       63.50   12.700586   27.215542
275        NaN       53.34       58.42   18.143695   24.947580

     min_expectancy  max_expectancy  energy_level_value  \
5              10.0            12.0                 0.8
9              14.0            16.0                 NaN
10             12.0            15.0                 0.8
14             12.0            15.0                 1.0
16             10.0            13.0                 0.8
..              ...             ...                 ...
260            10.0            14.0                 1.0
261            10.0            12.0                 0.6
268            13.0            13.0                 0.6
273            12.0            15.0                 0.8
275            10.0            12.0                 0.8

      energy_level_category  trainability_value trainability_category  \
5                 Energetic                 0.6             Agreeable
9                       NaN                 NaN                   NaN
10                Energetic                 1.0       Eager to Please
14   Needs Lots of Activity                 0.2       May be Stubborn
16                Energetic                 1.0       Eager to Please
..                      ...                 ...                   ...
260  Needs Lots of Activity                 0.2       May be Stubborn
261        Regular Exercise                 NaN                   NaN
268        Regular Exercise                 0.2       May be Stubborn
273               Energetic                 0.4           Independent
275               Energetic                 0.2       May be Stubborn

     demeanor_value        demeanor_category
5               0.6         Alert/Responsive
9               NaN                      NaN
10              0.6         Alert/Responsive
14              0.4  Reserved with Strangers
16              0.6         Alert/Responsive
..              ...                      ...
260             NaN                      NaN
261             NaN                      NaN
268             0.4  Reserved with Strangers
273             0.6         Alert/Responsive
275             0.4  Reserved with Strangers

[83 rows x 15 columns]

In [8]:
# Replace the NaN values in object type columns with None, that seems to work better with MySQL
# set the object type columns
cols_to_replace = ['energy_level_category', 'trainability_category', 'demeanor_category']

# Replace NaN with None in the specified columns
akc_dogs_df[cols_to_replace] = akc_dogs_df[cols_to_replace].where(pd.notna(akc_dogs_df[cols_to_replace]), None)

In [9]:
akc_dogs_df['popularity'].unique()

array(['148', '113', '60', '47', '58', nan, '175', '122', '186', '136',
       '85', '166', '90', '55', '17', '140', 'of', '87', '39', '6', '127',
       '124', '141', '43', '125', '106', '187', '144', '22', '46', '138',
       '118', '49', '130', '121', '35', '88', '103', '21', '84', '11',
       '100', '132', '26', '98', '62', '5', '51', '69', '179', '32', '68',
       '18', '185', '45', '33', '79', '64', '190', '75', '183', '143',
       '30', '38', '81', '162', '12', '56', '176', '67', '52', '188',
       '94', '27', '135', '157', '149', '161', '184', '91', '4', '134',
       '2', '9', '63', '78', '174', '3', '115', '177', '16', '66', '74',
       '145', '189', '24', '152', '155', '146', '77', '116', '159', '76',
       '73', '104', '95', '129', '173', '163', '1', '99', '147', '93',
       '71', '168', '37', '133', '29', '34', '110', '70', '19', '102',
       '150', '40', '126', '165', '97', '191', '108', '83', '72', '182',
       '54', '117', '92', '13', '156', '172', '171', '114', '170', '23',
       '7', '154', '50', '28', '160', '151', '181', '86', '142', '41',
       '8', '82', '48', '120', '59', '105', '158', '57', '164', '25',
       '44', '20', '14', '112', '178', '192', '123', '53', '153', '109',
       '80', '89', '180', '169', '131', '119', '96', '111', '137', '31',
       '36', '128', '107', '42', '61', '101', '65', '167', '10'],
      dtype=object)

In [10]:
# Convert popularity column to numeric, then replace NaN in the popularity column with 0
akc_dogs_df['popularity'] = pd.to_numeric(akc_dogs_df['popularity'], errors='coerce')
akc_dogs_df['popularity'].fillna(0, inplace=True)

/var/folders/tn/cf396_tn26g112g5gtc87pqm0000gn/T/ipykernel_2066/2929423701.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  akc_dogs_df['popularity'].fillna(0, inplace=True)

In [11]:
akc_dogs_df['popularity'].unique()
#akc_dogs_df.info()

array([148., 113.,  60.,  47.,  58.,   0., 175., 122., 186., 136.,  85.,
       166.,  90.,  55.,  17., 140.,  87.,  39.,   6., 127., 124., 141.,
        43., 125., 106., 187., 144.,  22.,  46., 138., 118.,  49., 130.,
       121.,  35.,  88., 103.,  21.,  84.,  11., 100., 132.,  26.,  98.,
        62.,   5.,  51.,  69., 179.,  32.,  68.,  18., 185.,  45.,  33.,
        79.,  64., 190.,  75., 183., 143.,  30.,  38.,  81., 162.,  12.,
        56., 176.,  67.,  52., 188.,  94.,  27., 135., 157., 149., 161.,
       184.,  91.,   4., 134.,   2.,   9.,  63.,  78., 174.,   3., 115.,
       177.,  16.,  66.,  74., 145., 189.,  24., 152., 155., 146.,  77.,
       116., 159.,  76.,  73., 104.,  95., 129., 173., 163.,   1.,  99.,
       147.,  93.,  71., 168.,  37., 133.,  29.,  34., 110.,  70.,  19.,
       102., 150.,  40., 126., 165.,  97., 191., 108.,  83.,  72., 182.,
        54., 117.,  92.,  13., 156., 172., 171., 114., 170.,  23.,   7.,
       154.,  50.,  28., 160., 151., 181.,  86., 142.,  41.,   8.,  82.,
        48., 120.,  59., 105., 158.,  57., 164.,  25.,  44.,  20.,  14.,
       112., 178., 192., 123.,  53., 153., 109.,  80.,  89., 180., 169.,
       131., 119.,  96., 111., 137.,  31.,  36., 128., 107.,  42.,  61.,
       101.,  65., 167.,  10.])

In [12]:
# let's see the max values in max_height, max_weight, and max_expectancy columns to get an idea of the data range in them
maxAkcValues = akc_dogs_df[['max_height', 'max_weight', 'max_expectancy']].max()
maxAkcValues

max_height         88.900000
max_weight        108.862169
max_expectancy     19.000000
dtype: float64

In [13]:
# let's do a final cleanup in case we missed any empty values
akc_dogs_df = akc_dogs_df.fillna({
    'breed': 'Unknown',
    'temperament': 'Unknown',
    'popularity': 0,
    'min_height': 0,
    'max_height': 0,
    'min_weight': 0,
    'max_weight': 0,
    'min_expectancy': 0,
    'max_expectancy': 0,
    'energy_level_value': 0,
    'energy_level_category': 'Unknown',
    'trainability_value': 0,
    'trainability_category': 'Unknown',
    'demeanor_value': 0,
    'demeanor_category': 'Unknown'
})

In [57]:
# Export the akc_dogs_df dataset to a .csv file
akc_dogs_df.to_csv('datasets/dog_breed_clean.csv', index=False, sep=',', encoding='utf-8')

# Pet Dataset

Let's clean up the pet dataset

In [14]:
# preview of the pet owners data
pet_owners_df.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A882831,*Hamilton,07/01/2023 06:12:00 PM,Jul 2023,03/25/2023,Adoption,NaN,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Black/White
1,A794011,Chunk,05/08/2019 06:20:00 PM,May 2019,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
2,A776359,Gizmo,07/18/2018 04:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
3,A821648,NaN,08/16/2020 11:38:00 AM,Aug 2020,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
4,A720371,Moose,02/13/2016 05:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff

In [15]:
print(pet_owners_df)

       Animal ID       Name                DateTime MonthYear Date of Birth  \
0        A882831  *Hamilton  07/01/2023 06:12:00 PM  Jul 2023    03/25/2023
1        A794011      Chunk  05/08/2019 06:20:00 PM  May 2019    05/02/2017
2        A776359      Gizmo  07/18/2018 04:02:00 PM  Jul 2018    07/12/2017
3        A821648        NaN  08/16/2020 11:38:00 AM  Aug 2020    08/16/2019
4        A720371      Moose  02/13/2016 05:59:00 PM  Feb 2016    10/08/2015
...          ...        ...                     ...       ...           ...
172595   A926855   *Eleanor  03/24/2025 04:30:00 PM  Mar 2025    11/18/2024
172596   A926900     *Ponzu  03/24/2025 05:34:00 PM  Mar 2025    03/18/2023
172597   A925467    *Oliver  03/24/2025 05:24:00 PM  Mar 2025    02/24/2023
172598   A926030    Kashmir  03/24/2025 05:49:00 PM  Mar 2025    03/04/2024
172599   A926980        NaN  03/24/2025 05:44:00 PM  Mar 2025    01/13/2025

       Outcome Type Outcome Subtype Animal Type Sex upon Outcome  \
0          Adoption             NaN         Cat    Neutered Male
1         Rto-Adopt             NaN         Cat    Neutered Male
2          Adoption             NaN         Dog    Neutered Male
3        Euthanasia             NaN       Other          Unknown
4          Adoption             NaN         Dog    Neutered Male
...             ...             ...         ...              ...
172595     Adoption             NaN         Cat    Spayed Female
172596     Adoption             NaN         Cat    Spayed Female
172597     Adoption             NaN         Cat    Neutered Male
172598     Adoption             NaN         Dog    Spayed Female
172599     Adoption             NaN         Dog    Neutered Male

       Age upon Outcome                               Breed  \
0              3 months              Domestic Shorthair Mix
1               2 years              Domestic Shorthair Mix
2                1 year             Chihuahua Shorthair Mix
3                1 year                             Raccoon
4              4 months  Anatol Shepherd/Labrador Retriever
...                 ...                                 ...
172595         4 months                  Domestic Shorthair
172596          2 years                  Domestic Shorthair
172597          2 years                  Domestic Shorthair
172598           1 year              Labrador Retriever Mix
172599         2 months                        Pit Bull Mix

                     Color
0              Black/White
1        Brown Tabby/White
2              White/Brown
3                     Gray
4                     Buff
...                    ...
172595              Tortie
172596        Orange Tabby
172597  Orange Tabby/White
172598         Black/White
172599               Brown

[172600 rows x 12 columns]

In [16]:
# Number of AKC dog breeds
len(akc_dogs_df['breed'].unique())

277

In [17]:
# Filter pet_owners_df to be only Animal Type of Dog
dog_pet_owners_df = pet_owners_df[pet_owners_df['Animal Type'] == 'Dog']

In [18]:
# Get an idea of how what kind of unique breed values are in pet
dog_pet_owners_df['Breed'].unique()

array(['Chihuahua Shorthair Mix', 'Anatol Shepherd/Labrador Retriever',
       'American Foxhound/Labrador Retriever', ..., 'Pit Bull/Bloodhound',
       'Shih Tzu/Cairn Terrier', 'French Bulldog/Pomeranian'],
      dtype=object)

In [19]:
# Assign all the dog breeds that are of mix to pet_contains_slash_df
pet_contains_slash_df = dog_pet_owners_df[dog_pet_owners_df['Breed'].str.contains('Mix', na=False)]
pet_contains_slash_df

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
2,A776359,Gizmo,07/18/2018 04:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
6,A659412,Princess,10/05/2020 02:37:00 PM,Oct 2020,03/24/2013,Adoption,NaN,Dog,Spayed Female,7 years,Chihuahua Shorthair Mix,Brown
17,A843327,*Mary,10/08/2021 01:25:00 PM,Oct 2021,09/29/2019,Transfer,Out State,Dog,Intact Female,2 years,Chihuahua Shorthair Mix,Black/White
20,A595061,Gypsy,08/18/2022 06:07:00 PM,Aug 2022,10/01/2010,Return to Owner,NaN,Dog,Spayed Female,11 years,Labrador Retriever Mix,Red/White
27,A856853,Jameson,05/20/2022 03:32:00 PM,May 2022,11/09/2021,Adoption,NaN,Dog,Neutered Male,6 months,Black Mouth Cur Mix,Brown/Black
...,...,...,...,...,...,...,...,...,...,...,...,...
172565,A737625,*Lt Winters,03/23/2025 06:06:00 PM,Mar 2025,05/01/2015,Adoption,NaN,Dog,Neutered Male,9 years,Pit Bull Mix,White
172574,A856897,Junior,05/12/2022 04:01:00 PM,May 2022,03/09/2022,Adoption,NaN,Dog,Neutered Male,2 months,German Shepherd Mix,Tricolor
172586,A926712,*Rocket Man,03/24/2025 04:19:00 PM,Mar 2025,09/15/2024,Adoption,NaN,Dog,Neutered Male,6 months,Carolina Dog Mix,Red/White
172598,A926030,Kashmir,03/24/2025 05:49:00 PM,Mar 2025,03/04/2024,Adoption,NaN,Dog,Spayed Female,1 year,Labrador Retriever Mix,Black/White
172599,A926980,NaN,03/24/2025 05:44:00 PM,Mar 2025,01/13/2025,Adoption,NaN,Dog,Neutered Male,2 months,Pit Bull Mix,Brown

59571 rows cotain " Mix" with the dog breed. We're going to remove " Mix" if the aditional breed wasn't provided with the dataset.

In [20]:
# Strip " Mix" from the Breed column
dog_pet_owners_df.loc[:, 'Breed'] = dog_pet_owners_df['Breed'].str.rstrip(' Mix')

In [21]:
# See how many breed matches are between the akc and pets datasets
breed_matches_df = dog_pet_owners_df['Breed'].isin(akc_dogs_df['breed']).sum()
print(f"Toal Pet Owners: {len(dog_pet_owners_df)}")
print(f"Total Pet Owners with AKC Breed Matches: {breed_matches_df}")

Toal Pet Owners: 93978
Total Pet Owners with AKC Breed Matches: 38879

In [22]:
dog_pet_owners_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93978 entries, 2 to 172599
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal ID         93978 non-null  object
 1   Name              79208 non-null  object
 2   DateTime          93978 non-null  object
 3   MonthYear         93978 non-null  object
 4   Date of Birth     93978 non-null  object
 5   Outcome Type      93951 non-null  object
 6   Outcome Subtype   31146 non-null  object
 7   Animal Type       93978 non-null  object
 8   Sex upon Outcome  93976 non-null  object
 9   Age upon Outcome  93974 non-null  object
 10  Breed             93978 non-null  object
 11  Color             93978 non-null  object
dtypes: object(12)
memory usage: 9.3+ MB

In [23]:
# See the unique values of Outcome Type column
dog_pet_owners_df['Outcome Type'].unique()

array(['Adoption', 'Return to Owner', 'Transfer', 'Rto-Adopt',
       'Euthanasia', 'Died', 'Missing', nan, 'Disposal', 'Stolen', 'Lost',
       'Relocate'], dtype=object)

In [24]:
# Create pet_trim_df dataframe with just the columns we want from dog_pet_owners_df
pet_trim_df = dog_pet_owners_df.loc[:, ['Name', 'Date of Birth', 'Outcome Type', 'Outcome Subtype', 'DateTime', 'Sex upon Outcome', 'Color', 'Age upon Outcome', 'Breed']]

In [25]:
# Rename the columns to be all lowercase with no spaces
pet_trim_df.rename(columns={'Name': 'name', 'Date of Birth': 'dob', 'Outcome Type': 'outcome_type', 'Outcome Subtype': 'outcome_subtype', 'DateTime': 'outcome_datetime', 'Sex upon Outcome': 'sex', 'Color': 'color', 'Age upon Outcome': 'age', 'Breed': 'breed'}, inplace=True)
pet_trim_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93978 entries, 2 to 172599
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              79208 non-null  object
 1   dob               93978 non-null  object
 2   outcome_type      93951 non-null  object
 3   outcome_subtype   31146 non-null  object
 4   outcome_datetime  93978 non-null  object
 5   sex               93976 non-null  object
 6   color             93978 non-null  object
 7   age               93974 non-null  object
 8   breed             93978 non-null  object
dtypes: object(9)
memory usage: 7.2+ MB

In [26]:
# let's look for any rows with missing values
pet_rows_with_missing_values = pet_trim_df[pet_trim_df.isna().any(axis=1)]
print(pet_rows_with_missing_values)

               name         dob     outcome_type outcome_subtype  \
2             Gizmo  07/12/2017         Adoption             NaN
4             Moose  10/08/2015         Adoption             NaN
6          Princess  03/24/2013         Adoption             NaN
12            Tulip  08/06/2019         Adoption             NaN
16            Fiona  06/01/2018  Return to Owner             NaN
...             ...         ...              ...             ...
172574       Junior  03/09/2022         Adoption             NaN
172586  *Rocket Man  09/15/2024         Adoption             NaN
172591   *Charlotte  12/02/2024         Adoption             NaN
172598      Kashmir  03/04/2024         Adoption             NaN
172599          NaN  01/13/2025         Adoption             NaN

              outcome_datetime            sex        color       age  \
2       07/18/2018 04:02:00 PM  Neutered Male  White/Brown    1 year
4       02/13/2016 05:59:00 PM  Neutered Male         Buff  4 months
6       10/05/2020 02:37:00 PM  Spayed Female        Brown   7 years
12      08/19/2021 07:36:00 PM  Spayed Female  Black/White   2 years
16      06/01/2020 01:24:00 PM  Intact Female   White/Blue   2 years
...                        ...            ...          ...       ...
172574  05/12/2022 04:01:00 PM  Neutered Male     Tricolor  2 months
172586  03/24/2025 04:19:00 PM  Neutered Male    Red/White  6 months
172591  03/24/2025 04:47:00 PM  Spayed Female  Black/White  3 months
172598  03/24/2025 05:49:00 PM  Spayed Female  Black/White    1 year
172599  03/24/2025 05:44:00 PM  Neutered Male        Brown  2 months

                                     breed
2                      Chihuahua Shorthair
4       Anatol Shepherd/Labrador Retriever
6                      Chihuahua Shorthair
12       Border Collie/Cardigan Welsh Corg
16                                Pit Bull
...                                    ...
172574                     German Shepherd
172586                        Carolina Dog
172591    Labrador Retriever/Border Collie
172598                  Labrador Retriever
172599                            Pit Bull

[70887 rows x 9 columns]

In [27]:
# Let's replace the NaN values for the name with Unknown
pet_trim_df['name'] = pet_trim_df['name'].replace(np.nan, 'Unknown')

In [28]:
# Let's replace the NaN values for the outcome_type with None
pet_trim_df['outcome_type'].fillna('None', inplace=True)

/var/folders/tn/cf396_tn26g112g5gtc87pqm0000gn/T/ipykernel_2066/360236105.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pet_trim_df['outcome_type'].fillna('None', inplace=True)

In [29]:
# Drop any remaining rows with NaN values
pet_trim_df.dropna(inplace=True)

In [30]:
# Convert dob to MySQL friendly date format
pet_trim_df['dob'] = pd.to_datetime(pet_trim_df['dob'])
pet_trim_df['dob'] = pet_trim_df['dob'].dt.strftime('%Y-%m-%d')

In [31]:
# Convert outcome_datetime to MySQL friendly date/time format
pet_trim_df['outcome_datetime'] = pd.to_datetime(pet_trim_df['outcome_datetime'])
pet_trim_df['outcome_datetime'] = pet_trim_df['outcome_datetime'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [32]:
#Let's keep only rows where pet breed matches the akc_dogs breed
akc_breeds = akc_dogs_df['breed'].unique()
filtered_pet_trim_df = pet_trim_df[pet_trim_df['breed'].isin(akc_breeds)]
len(filtered_pet_trim_df) # output number of clean breed rows

13125

In [38]:
# let's do a final cleanup in case we missed any empty values
filtered_pet_trim_df = filtered_pet_trim_df.fillna({
    'name': 'Unknown',
    'outcome_type': 'Unknown',
    'outcome_subtype': 'Unknown',
    'sex': 'Unknown',
    'color': 'Unknown',
    'age': 'Unknown',
    'breed': 'Unknown'
})

In [40]:
# Export the filtered_pet_trim_df dataset to a .csv file
filtered_pet_trim_df.to_csv('datasets/pet_clean.csv', index=False, sep=',', encoding='utf-8')

##Start MySQL Portion

In [33]:
# Load necessary packages:
from sqlalchemy import create_engine, Column, String, Integer, Boolean, BigInteger, Float, text # Database navigation
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import insert
import mysql.connector

In [37]:
# let's look for any rows with missing values
pet_rows_with_missing_values = pet_trim_df[pet_trim_df.isna().any(axis=1)]
print(pet_rows_with_missing_values)

Empty DataFrame
Columns: [name, dob, outcome_type, outcome_subtype, outcome_datetime, sex, color, age, breed]
Index: []

In [34]:
#define mysql connection variables
conn = mysql.connector.connect(
        host="localhost", # This is my local instance number when you open MySQL Workbench.
        user="root", # This is my username for MySQL Workbench
        password="karateChop") # We wrote this password down in our first class!

# Create a cursor object using the cursor() method
cursor = conn.cursor()

# CREATE DATABASE if it does not already exist for assignment 7
cursor.execute("CREATE DATABASE IF NOT EXISTS pet_puffs")

In [35]:
# Time to connect to the database using SQL Alchemy:
DATABASE_URL = "mysql+mysqlconnector://root:karateChop@localhost/pet_puffs" # Use MySQL Connector to connect to the database
engine = create_engine(DATABASE_URL) # Creates a connection to the MySQL database

print("Connected to MySQL database successfully!")
# I'm really not sure why I picked karateChop as a password, must've been something I saw that day. Glad I wrote it down!

Connected to MySQL database successfully!

In [ ]:
Create the database tables

In [36]:
cursor = conn.cursor()

# let's create our dog_breed table
create_breed_table_query = """CREATE TABLE IF NOT EXISTS dog_breed (
                              id INT AUTO_INCREMENT PRIMARY KEY,
                              breed VARCHAR(255),
                              temperament VARCHAR(255),
                              popularity FLOAT,
                              min_height FLOAT,
                              max_height FLOAT,
                              min_weight FLOAT,
                              max_weight FLOAT,
                              min_expectancy FLOAT,
                              max_expectancy FLOAT,
                              energy_level_value FLOAT,
                              energy_level_category VARCHAR(255),
                              trainability_value FLOAT,
                              trainability_category VARCHAR(255),
                              demeanor_value FLOAT,
                              demeanor_category VARCHAR(255),
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
                              );
                           """
# Execute the create_breed_table_query
with engine.connect() as connection:
    connection.execute(text(create_breed_table_query))

print("create_breed_table_query table created successfully!") # output this string if the query worked # run our query to create the dog_breed table

create_breed_table_query table created successfully!

In [37]:
cursor = conn.cursor()

# let's create our pet table
create_pet_table_query = """CREATE TABLE IF NOT EXISTS pet (
                              id INT AUTO_INCREMENT PRIMARY KEY,
                              name VARCHAR(255),
                              dob DATE,
                              sex VARCHAR(255),
                              color VARCHAR(255),
                              age VARCHAR(255),
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                              dog_breed_id INT,
                              FOREIGN KEY (dog_breed_id) REFERENCES dog_breed(id)
                              );
                           """
# Execute the create_breed_table_query
with engine.connect() as connection:
    connection.execute(text(create_pet_table_query))

# let's create our pet_outcome table
create_pet_outcome_table_query = """CREATE TABLE IF NOT EXISTS pet_outcome (
                              id INT AUTO_INCREMENT PRIMARY KEY,
                              outcome_type VARCHAR(255),
                              outcome_subtype VARCHAR(255),
                              outcome_datetime DATETIME,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                              updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                              pet_id INT,
                              FOREIGN KEY (pet_id) REFERENCES pet(id)
                              );
                           """
# Execute the create_breed_table_query
with engine.connect() as connection:
    connection.execute(text(create_pet_outcome_table_query))

print("created our pet and pet_outcome tables created successfully!") # output this string if the query worked # run our query to create the dog_breed table

created our pet and pet_outcome tables created successfully!

Insert our data into the dog_breed, pet, and pet_outcome tables

In [58]:
cursor.execute("USE pet_puffs;")  # specify the pet_puffs database

# for look to go through each row of the akc_dogs_df
for index, dog in akc_dogs_df.iterrows():

  # INSERT into dog_breed table
  cursor.execute("""INSERT INTO dog_breed (
                      breed,
                      temperament,
                      popularity,
                      min_height,
                      max_height,
                      min_weight,
                      max_weight,
                      min_expectancy,
                      max_expectancy,
                      energy_level_value,
                      energy_level_category,
                      trainability_value,
                      trainability_category,
                      demeanor_value,
                      demeanor_category
                      )
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
                 """, (
                      dog['breed'],
                      dog['temperament'],
                      dog['popularity'],
                      dog['min_height'],
                      dog['max_height'],
                      dog['min_weight'],
                      dog['max_weight'],
                      dog['min_expectancy'],
                      dog['max_expectancy'],
                      dog['energy_level_value'],
                      dog['energy_level_category'],
                      dog['trainability_value'],
                      dog['trainability_category'],
                      dog['demeanor_value'],
                      dog['demeanor_category']
                 ))

# Commit the transaction
conn.commit()

print("dog_breed table is populated")

dog_breed table is populated

In [42]:
cursor.execute("USE pet_puffs;")  # specify the pet_puffs database

# Fairly heavy loop and conditional logic for the pet and pet_outcome INSERTS
for index, pet in filtered_pet_trim_df.iterrows():
    current_breed = pet['breed']  # set the current breed to current_breed
    # Run the SQL to get the id of the breed that matches the current_breed
    cursor.execute("""SELECT id
                      FROM dog_breed
                      WHERE breed = %s""", (current_breed,))  # convert to tuple

    breed_id = cursor.fetchone()  # output the dog_breed id to the breed_id variable
    # Check if breed_id is found, otherwise insert None
    breed_id = breed_id[0] if breed_id else None

    # Run the INSERT into pet table
    cursor.execute("""INSERT INTO pet (
                        name,
                        dob,
                        sex,
                        color,
                        age,
                        dog_breed_id
                      )
                      VALUES (%s, %s, %s, %s, %s, %s)
                   """, (
                        pet['name'],
                        pet['dob'],
                        pet['sex'],
                        pet['color'],
                        pet['age'],
                        breed_id
                  ))

    # Get the last inserted pet ID
    pet_id = cursor.lastrowid
    print(pet_id)

    # If pet_outcome is not equal to None, then insert a record into the pet_outcome table
    if pet['outcome_type'] != 'None':
        cursor.execute("""INSERT INTO pet_outcome (
                            outcome_type,
                            outcome_subtype,
                            outcome_datetime,
                            pet_id
                          )
                          VALUES (%s, %s, %s, %s)
                       """, (
                            pet['outcome_type'],
                            pet['outcome_subtype'],
                            pet['outcome_datetime'],
                            pet_id
                       ))

# Commit the transaction
conn.commit()

print("pet and pet_outcome table is populated")

InternalError: Unread result found

In [ ]:
#Close the database connection :)
# mycursor.close()
# conn.close()

Let's populate the pet and pet_outcome tables. This will be a little tricky with the loops and conditionals, so we'll practice the the logic first.

In [ ]:
# Create and start SSH tunnel to populate the pet and pet_outcome tables
with SSHTunnelForwarder(
    (ssh_host, ssh_port),
    ssh_username=ssh_username,
    ssh_password=ssh_password,
    remote_bind_address=(mysql_host, mysql_port),
) as server:
    print(f"SSH tunnel established on port {server.local_bind_port}")
    # MySQL connection must go within the with

    # Connect to MySQL using SSH tunnel
    conn = mysql.connector.connect(
            host="127.0.0.1", # Use localhost since we're connected via SSH
            port=server.local_bind_port,
            user=mysql_username,
            password=mysql_password,
            database="data_warehousing_final",
        )

    cursor = conn.cursor()

    # Test the loop and conditional logic for the INSERTS
    for index, pet in pet_trim_df.iterrows():
        current_breed = pet['breed'] # set the current breed to current_breed
        # Run the SQL to get the id of the breed that matches the current_breed
        cursor.execute("""SELECT id
                        FROM dog_breed
                        WHERE breed = %s""", (
                            (current_breed,) # convert to tuple
                        ))
        breed_id = cursor.fetchone() # output the dog_breed id to the breed_id variable
        # Check if breed_id is found, otherwise insert None
        breed_id = breed_id[0] if breed_id else None

        # Run the INSERT into pet table
        cursor.execute("""INSERT IGNORE INTO pet (
                            name,
                            dob,
                            sex,
                            color,
                            age,
                            dog_breed_id
                            )
                          VALUES (%s, %s, %s, %s, %s, %s)
                       """, (
                            pet['name'],
                            pet['dob'],
                            pet['sex'],
                            pet['color'],
                            pet['age'],
                            breed_id
                      ))

        # Get the last inserted pet ID
        pet_id = cursor.lastrowid
        print(pet_id)

        # If pet_outcome is not equal to None, then insert a record into the pet_outcome table
        if pet['outcome_type'] != 'None':
            cursor.execute("""INSERT IGNORE INTO pet_outcome (
                                outcome_type,
                                outcome_subtype,
                                outcome_datetime,
                                pet_id
                                )
                              VALUES (%s, %s, %s, %s)
                           """, (
                                pet['outcome_type'],
                                pet['outcome_subtype'],
                                pet['outcome_datetime'],
                                pet_id
                           ))

    conn.commit() # Commit the changes after the loop
    conn.close() # We always close the db of course!

Streaming output truncated to the last 5000 lines.
40579
40580
40581
40582
40583
40584
40585
40586
40587
40588
40589
40590
40591
40592
40593
40594
40595
40596
40597
40598
40599
40600
40601
40602
40603
40604
40605
40606
40607
40608
40609
40610
40611
40612
40613
40614
40615
40616
40617
40618
40619
40620
40621
40622
40623
40624
40625
40626
40627
40628
40629
40630
40631
40632
40633
40634
40635
40636
40637
40638
40639
40640
40641
40642
40643
40644
40645
40646
40647
40648
40649
40650
40651
40652
40653
40654
40655
40656
40657
40658
40659
40660
40661
40662
40663
40664
40665
40666
40667
40668
40669
40670
40671
40672
40673
40674
40675
40676
40677
40678
40679
40680
40681
40682
40683
40684
40685
40686
40687
40688
40689
40690
40691
40692
40693
40694
40695
40696
40697
40698
40699
40700
40701
40702
40703
40704
40705
40706
40707
40708
40709
40710
40711
40712
40713
40714
40715
40716
40717
40718
40719
40720
40721
40722
40723
40724
40725
40726
40727
40728
40729
40730
40731
40732
40733
40734
40735
40736
40737
40738
40739
40740
40741
40742
40743
40744
40745
40746
40747
40748
40749
40750
40751
40752
40753
40754
40755
40756
40757
40758
40759
40760
40761
40762
40763
40764
40765
40766
40767
40768
40769
40770
40771
40772
40773
40774
40775
40776
40777
40778
40779
40780
40781
40782
40783
40784
40785
40786
40787
40788
40789
40790
40791
40792
40793
40794
40795
40796
40797
40798
40799
40800
40801
40802
40803
40804
40805
40806
40807
40808
40809
40810
40811
40812
40813
40814
40815
40816
40817
40818
40819
40820
40821
40822
40823
40824
40825
40826
40827
40828
40829
40830
40831
40832
40833
40834
40835
40836
40837
40838
40839
40840
40841
40842
40843
40844
40845
40846
40847
40848
40849
40850
40851
40852
40853
40854
40855
40856
40857
40858
40859
40860
40861
40862
40863
40864
40865
40866
40867
40868
40869
40870
40871
40872
40873
40874
40875
40876
40877
40878
40879
40880
40881
40882
40883
40884
40885
40886
40887
40888
40889
40890
40891
40892
40893
40894
40895
40896
40897
40898
40899
40900
40901
40902
40903
40904
40905
40906
40907
40908
40909
40910
40911
40912
40913
40914
40915
40916
40917
40918
40919
40920
40921
40922
40923
40924
40925
40926
40927
40928
40929
40930
40931
40932
40933
40934
40935
40936
40937
40938
40939
40940
40941
40942
40943
40944
40945
40946
40947
40948
40949
40950
40951
40952
40953
40954
40955
40956
40957
40958
40959
40960
40961
40962
40963
40964
40965
40966
40967
40968
40969
40970
40971
40972
40973
40974
40975
40976
40977
40978
40979
40980
40981
40982
40983
40984
40985
40986
40987
40988
40989
40990
40991
40992
40993
40994
40995
40996
40997
40998
40999
41000
41001
41002
41003
41004
41005
41006
41007
41008
41009
41010
41011
41012
41013
41014
41015
41016
41017
41018
41019
41020
41021
41022
41023
41024
41025
41026
41027
41028
41029
41030
41031
41032
41033
41034
41035
41036
41037
41038
41039
41040
41041
41042
41043
41044
41045
41046
41047
41048
41049
41050
41051
41052
41053
41054
41055
41056
41057
41058
41059
41060
41061
41062
41063
41064
41065
41066
41067
41068
41069
41070
41071
41072
41073
41074
41075
41076
41077
41078
41079
41080
41081
41082
41083
41084
41085
41086
41087
41088
41089
41090
41091
41092
41093
41094
41095
41096
41097
41098
41099
41100
41101
41102
41103
41104
41105
41106
41107
41108
41109
41110
41111
41112
41113
41114
41115
41116
41117
41118
41119
41120
41121
41122
41123
41124
41125
41126
41127
41128
41129
41130
41131
41132
41133
41134
41135
41136
41137
41138
41139
41140
41141
41142
41143
41144
41145
41146
41147
41148
41149
41150
41151
41152
41153
41154
41155
41156
41157
41158
41159
41160
41161
41162
41163
41164
41165
41166
41167
41168
41169
41170
41171
41172
41173
41174
41175
41176
41177
41178
41179
41180
41181
41182
41183
41184
41185
41186
41187
41188
41189
41190
41191
41192
41193
41194
41195
41196
41197
41198
41199
41200
41201
41202
41203
41204
41205
41206
41207
41208
41209
41210
41211
41212
41213
41214
41215
41216
41217
41218
41219
41220
41221
41222
41223
41224
41225
41226
41227
41228
41229
41230
41231
41232
41233
41234
41235
41236
41237
41238
41239
41240
41241
41242
41243
41244
41245
41246
41247
41248
41249
41250
41251
41252
41253
41254
41255
41256
41257
41258
41259
41260
41261
41262
41263
41264
41265
41266
41267
41268
41269
41270
41271
41272
41273
41274
41275
41276
41277
41278
41279
41280
41281
41282
41283
41284
41285
41286
41287
41288
41289
41290
41291
41292
41293
41294
41295
41296
41297
41298
41299
41300
41301
41302
41303
41304
41305
41306
41307
41308
41309
41310
41311
41312
41313
41314
41315
41316
41317
41318
41319
41320
41321
41322
41323
41324
41325
41326
41327
41328
41329
41330
41331
41332
41333
41334
41335
41336
41337
41338
41339
41340
41341
41342
41343
41344
41345
41346
41347
41348
41349
41350
41351
41352
41353
41354
41355
41356
41357
41358
41359
41360
41361
41362
41363
41364
41365
41366
41367
41368
41369
41370
41371
41372
41373
41374
41375
41376
41377
41378
41379
41380
41381
41382
41383
41384
41385
41386
41387
41388
41389
41390
41391
41392
41393
41394
41395
41396
41397
41398
41399
41400
41401
41402
41403
41404
41405
41406
41407
41408
41409
41410
41411
41412
41413
41414
41415
41416
41417
41418
41419
41420
41421
41422
41423
41424
41425
41426
41427
41428
41429
41430
41431
41432
41433
41434
41435
41436
41437
41438
41439
41440
41441
41442
41443
41444
41445
41446
41447
41448
41449
41450
41451
41452
41453
41454
41455
41456
41457
41458
41459
41460
41461
41462
41463
41464
41465
41466
41467
41468
41469
41470
41471
41472
41473
41474
41475
41476
41477
41478
41479
41480
41481
41482
41483
41484
41485
41486
41487
41488
41489
41490
41491
41492
41493
41494
41495
41496
41497
41498
41499
41500
41501
41502
41503
41504
41505
41506
41507
41508
41509
41510
41511
41512
41513
41514
41515
41516
41517
41518
41519
41520
41521
41522
41523
41524
41525
41526
41527
41528
41529
41530
41531
41532
41533
41534
41535
41536
41537
41538
41539
41540
41541
41542
41543
41544
41545
41546
41547
41548
41549
41550
41551
41552
41553
41554
41555
41556
41557
41558
41559
41560
41561
41562
41563
41564
41565
41566
41567
41568
41569
41570
41571
41572
41573
41574
41575
41576
41577
41578
41579
41580
41581
41582
41583
41584
41585
41586
41587
41588
41589
41590
41591
41592
41593
41594
41595
41596
41597
41598
41599
41600
41601
41602
41603
41604
41605
41606
41607
41608
41609
41610
41611
41612
41613
41614
41615
41616
41617
41618
41619
41620
41621
41622
41623
41624
41625
41626
41627
41628
41629
41630
41631
41632
41633
41634
41635
41636
41637
41638
41639
41640
41641
41642
41643
41644
41645
41646
41647
41648
41649
41650
41651
41652
41653
41654
41655
41656
41657
41658
41659
41660
41661
41662
41663
41664
41665
41666
41667
41668
41669
41670
41671
41672
41673
41674
41675
41676
41677
41678
41679
41680
41681
41682
41683
41684
41685
41686
41687
41688
41689
41690
41691
41692
41693
41694
41695
41696
41697
41698
41699
41700
41701
41702
41703
41704
41705
41706
41707
41708
41709
41710
41711
41712
41713
41714
41715
41716
41717
41718
41719
41720
41721
41722
41723
41724
41725
41726
41727
41728
41729
41730
41731
41732
41733
41734
41735
41736
41737
41738
41739
41740
41741
41742
41743
41744
41745
41746
41747
41748
41749
41750
41751
41752
41753
41754
41755
41756
41757
41758
41759
41760
41761
41762
41763
41764
41765
41766
41767
41768
41769
41770
41771
41772
41773
41774
41775
41776
41777
41778
41779
41780
41781
41782
41783
41784
41785
41786
41787
41788
41789
41790
41791
41792
41793
41794
41795
41796
41797
41798
41799
41800
41801
41802
41803
41804
41805
41806
41807
41808
41809
41810
41811
41812
41813
41814
41815
41816
41817
41818
41819
41820
41821
41822
41823
41824
41825
41826
41827
41828
41829
41830
41831
41832
41833
41834
41835
41836
41837
41838
41839
41840
41841
41842
41843
41844
41845
41846
41847
41848
41849
41850
41851
41852
41853
41854
41855
41856
41857
41858
41859
41860
41861
41862
41863
41864
41865
41866
41867
41868
41869
41870
41871
41872
41873
41874
41875
41876
41877
41878
41879
41880
41881
41882
41883
41884
41885
41886
41887
41888
41889
41890
41891
41892
41893
41894
41895
41896
41897
41898
41899
41900
41901
41902
41903
41904
41905
41906
41907
41908
41909
41910
41911
41912
41913
41914
41915
41916
41917
41918
41919
41920
41921
41922
41923
41924
41925
41926
41927
41928
41929
41930
41931
41932
41933
41934
41935
41936
41937
41938
41939
41940
41941
41942
41943
41944
41945
41946
41947
41948
41949
41950
41951
41952
41953
41954
41955
41956
41957
41958
41959
41960
41961
41962
41963
41964
41965
41966
41967
41968
41969
41970
41971
41972
41973
41974
41975
41976
41977
41978
41979
41980
41981
41982
41983
41984
41985
41986
41987
41988
41989
41990
41991
41992
41993
41994
41995
41996
41997
41998
41999
42000
42001
42002
42003
42004
42005
42006
42007
42008
42009
42010
42011
42012
42013
42014
42015
42016
42017
42018
42019
42020
42021
42022
42023
42024
42025
42026
42027
42028
42029
42030
42031
42032
42033
42034
42035
42036
42037
42038
42039
42040
42041
42042
42043
42044
42045
42046
42047
42048
42049
42050
42051
42052
42053
42054
42055
42056
42057
42058
42059
42060
42061
42062
42063
42064
42065
42066
42067
42068
42069
42070
42071
42072
42073
42074
42075
42076
42077
42078
42079
42080
42081
42082
42083
42084
42085
42086
42087
42088
42089
42090
42091
42092
42093
42094
42095
42096
42097
42098
42099
42100
42101
42102
42103
42104
42105
42106
42107
42108
42109
42110
42111
42112
42113
42114
42115
42116
42117
42118
42119
42120
42121
42122
42123
42124
42125
42126
42127
42128
42129
42130
42131
42132
42133
42134
42135
42136
42137
42138
42139
42140
42141
42142
42143
42144
42145
42146
42147
42148
42149
42150
42151
42152
42153
42154
42155
42156
42157
42158
42159
42160
42161
42162
42163
42164
42165
42166
42167
42168
42169
42170
42171
42172
42173
42174
42175
42176
42177
42178
42179
42180
42181
42182
42183
42184
42185
42186
42187
42188
42189
42190
42191
42192
42193
42194
42195
42196
42197
42198
42199
42200
42201
42202
42203
42204
42205
42206
42207
42208
42209
42210
42211
42212
42213
42214
42215
42216
42217
42218
42219
42220
42221
42222
42223
42224
42225
42226
42227
42228
42229
42230
42231
42232
42233
42234
42235
42236
42237
42238
42239
42240
42241
42242
42243
42244
42245
42246
42247
42248
42249
42250
42251
42252
42253
42254
42255
42256
42257
42258
42259
42260
42261
42262
42263
42264
42265
42266
42267
42268
42269
42270
42271
42272
42273
42274
42275
42276
42277
42278
42279
42280
42281
42282
42283
42284
42285
42286
42287
42288
42289
42290
42291
42292
42293
42294
42295
42296
42297
42298
42299
42300
42301
42302
42303
42304
42305
42306
42307
42308
42309
42310
42311
42312
42313
42314
42315
42316
42317
42318
42319
42320
42321
42322
42323
42324
42325
42326
42327
42328
42329
42330
42331
42332
42333
42334
42335
42336
42337
42338
42339
42340
42341
42342
42343
42344
42345
42346
42347
42348
42349
42350
42351
42352
42353
42354
42355
42356
42357
42358
42359
42360
42361
42362
42363
42364
42365
42366
42367
42368
42369
42370
42371
42372
42373
42374
42375
42376
42377
42378
42379
42380
42381
42382
42383
42384
42385
42386
42387
42388
42389
42390
42391
42392
42393
42394
42395
42396
42397
42398
42399
42400
42401
42402
42403
42404
42405
42406
42407
42408
42409
42410
42411
42412
42413
42414
42415
42416
42417
42418
42419
42420
42421
42422
42423
42424
42425
42426
42427
42428
42429
42430
42431
42432
42433
42434
42435
42436
42437
42438
42439
42440
42441
42442
42443
42444
42445
42446
42447
42448
42449
42450
42451
42452
42453
42454
42455
42456
42457
42458
42459
42460
42461
42462
42463
42464
42465
42466
42467
42468
42469
42470
42471
42472
42473
42474
42475
42476
42477
42478
42479
42480
42481
42482
42483
42484
42485
42486
42487
42488
42489
42490
42491
42492
42493
42494
42495
42496
42497
42498
42499
42500
42501
42502
42503
42504
42505
42506
42507
42508
42509
42510
42511
42512
42513
42514
42515
42516
42517
42518
42519
42520
42521
42522
42523
42524
42525
42526
42527
42528
42529
42530
42531
42532
42533
42534
42535
42536
42537
42538
42539
42540
42541
42542
42543
42544
42545
42546
42547
42548
42549
42550
42551
42552
42553
42554
42555
42556
42557
42558
42559
42560
42561
42562
42563
42564
42565
42566
42567
42568
42569
42570
42571
42572
42573
42574
42575
42576
42577
42578
42579
42580
42581
42582
42583
42584
42585
42586
42587
42588
42589
42590
42591
42592
42593
42594
42595
42596
42597
42598
42599
42600
42601
42602
42603
42604
42605
42606
42607
42608
42609
42610
42611
42612
42613
42614
42615
42616
42617
42618
42619
42620
42621
42622
42623
42624
42625
42626
42627
42628
42629
42630
42631
42632
42633
42634
42635
42636
42637
42638
42639
42640
42641
42642
42643
42644
42645
42646
42647
42648
42649
42650
42651
42652
42653
42654
42655
42656
42657
42658
42659
42660
42661
42662
42663
42664
42665
42666
42667
42668
42669
42670
42671
42672
42673
42674
42675
42676
42677
42678
42679
42680
42681
42682
42683
42684
42685
42686
42687
42688
42689
42690
42691
42692
42693
42694
42695
42696
42697
42698
42699
42700
42701
42702
42703
42704
42705
42706
42707
42708
42709
42710
42711
42712
42713
42714
42715
42716
42717
42718
42719
42720
42721
42722
42723
42724
42725
42726
42727
42728
42729
42730
42731
42732
42733
42734
42735
42736
42737
42738
42739
42740
42741
42742
42743
42744
42745
42746
42747
42748
42749
42750
42751
42752
42753
42754
42755
42756
42757
42758
42759
42760
42761
42762
42763
42764
42765
42766
42767
42768
42769
42770
42771
42772
42773
42774
42775
42776
42777
42778
42779
42780
42781
42782
42783
42784
42785
42786
42787
42788
42789
42790
42791
42792
42793
42794
42795
42796
42797
42798
42799
42800
42801
42802
42803
42804
42805
42806
42807
42808
42809
42810
42811
42812
42813
42814
42815
42816
42817
42818
42819
42820
42821
42822
42823
42824
42825
42826
42827
42828
42829
42830
42831
42832
42833
42834
42835
42836
42837
42838
42839
42840
42841
42842
42843
42844
42845
42846
42847
42848
42849
42850
42851
42852
42853
42854
42855
42856
42857
42858
42859
42860
42861
42862
42863
42864
42865
42866
42867
42868
42869
42870
42871
42872
42873
42874
42875
42876
42877
42878
42879
42880
42881
42882
42883
42884
42885
42886
42887
42888
42889
42890
42891
42892
42893
42894
42895
42896
42897
42898
42899
42900
42901
42902
42903
42904
42905
42906
42907
42908
42909
42910
42911
42912
42913
42914
42915
42916
42917
42918
42919
42920
42921
42922
42923
42924
42925
42926
42927
42928
42929
42930
42931
42932
42933
42934
42935
42936
42937
42938
42939
42940
42941
42942
42943
42944
42945
42946
42947
42948
42949
42950
42951
42952
42953
42954
42955
42956
42957
42958
42959
42960
42961
42962
42963
42964
42965
42966
42967
42968
42969
42970
42971
42972
42973
42974
42975
42976
42977
42978
42979
42980
42981
42982
42983
42984
42985
42986
42987
42988
42989
42990
42991
42992
42993
42994
42995
42996
42997
42998
42999
43000
43001
43002
43003
43004
43005
43006
43007
43008
43009
43010
43011
43012
43013
43014
43015
43016
43017
43018
43019
43020
43021
43022
43023
43024
43025
43026
43027
43028
43029
43030
43031
43032
43033
43034
43035
43036
43037
43038
43039
43040
43041
43042
43043
43044
43045
43046
43047
43048
43049
43050
43051
43052
43053
43054
43055
43056
43057
43058
43059
43060
43061
43062
43063
43064
43065
43066
43067
43068
43069
43070
43071
43072
43073
43074
43075
43076
43077
43078
43079
43080
43081
43082
43083
43084
43085
43086
43087
43088
43089
43090
43091
43092
43093
43094
43095
43096
43097
43098
43099
43100
43101
43102
43103
43104
43105
43106
43107
43108
43109
43110
43111
43112
43113
43114
43115
43116
43117
43118
43119
43120
43121
43122
43123
43124
43125
43126
43127
43128
43129
43130
43131
43132
43133
43134
43135
43136
43137
43138
43139
43140
43141
43142
43143
43144
43145
43146
43147
43148
43149
43150
43151
43152
43153
43154
43155
43156
43157
43158
43159
43160
43161
43162
43163
43164
43165
43166
43167
43168
43169
43170
43171
43172
43173
43174
43175
43176
43177
43178
43179
43180
43181
43182
43183
43184
43185
43186
43187
43188
43189
43190
43191
43192
43193
43194
43195
43196
43197
43198
43199
43200
43201
43202
43203
43204
43205
43206
43207
43208
43209
43210
43211
43212
43213
43214
43215
43216
43217
43218
43219
43220
43221
43222
43223
43224
43225
43226
43227
43228
43229
43230
43231
43232
43233
43234
43235
43236
43237
43238
43239
43240
43241
43242
43243
43244
43245
43246
43247
43248
43249
43250
43251
43252
43253
43254
43255
43256
43257
43258
43259
43260
43261
43262
43263
43264
43265
43266
43267
43268
43269
43270
43271
43272
43273
43274
43275
43276
43277
43278
43279
43280
43281
43282
43283
43284
43285
43286
43287
43288
43289
43290
43291
43292
43293
43294
43295
43296
43297
43298
43299
43300
43301
43302
43303
43304
43305
43306
43307
43308
43309
43310
43311
43312
43313
43314
43315
43316
43317
43318
43319
43320
43321
43322
43323
43324
43325
43326
43327
43328
43329
43330
43331
43332
43333
43334
43335
43336
43337
43338
43339
43340
43341
43342
43343
43344
43345
43346
43347
43348
43349
43350
43351
43352
43353
43354
43355
43356
43357
43358
43359
43360
43361
43362
43363
43364
43365
43366
43367
43368
43369
43370
43371
43372
43373
43374
43375
43376
43377
43378
43379
43380
43381
43382
43383
43384
43385
43386
43387
43388
43389
43390
43391
43392
43393
43394
43395
43396
43397
43398
43399
43400
43401
43402
43403
43404
43405
43406
43407
43408
43409
43410
43411
43412
43413
43414
43415
43416
43417
43418
43419
43420
43421
43422
43423
43424
43425
43426
43427
43428
43429
43430
43431
43432
43433
43434
43435
43436
43437
43438
43439
43440
43441
43442
43443
43444
43445
43446
43447
43448
43449
43450
43451
43452
43453
43454
43455
43456
43457
43458
43459
43460
43461
43462
43463
43464
43465
43466
43467
43468
43469
43470
43471
43472
43473
43474
43475
43476
43477
43478
43479
43480
43481
43482
43483
43484
43485
43486
43487
43488
43489
43490
43491
43492
43493
43494
43495
43496
43497
43498
43499
43500
43501
43502
43503
43504
43505
43506
43507
43508
43509
43510
43511
43512
43513
43514
43515
43516
43517
43518
43519
43520
43521
43522
43523
43524
43525
43526
43527
43528
43529
43530
43531
43532
43533
43534
43535
43536
43537
43538
43539
43540
43541
43542
43543
43544
43545
43546
43547
43548
43549
43550
43551
43552
43553
43554
43555
43556
43557
43558
43559
43560
43561
43562
43563
43564
43565
43566
43567
43568
43569
43570
43571
43572
43573
43574
43575
43576
43577
43578
43579
43580
43581
43582
43583
43584
43585
43586
43587
43588
43589
43590
43591
43592
43593
43594
43595
43596
43597
43598
43599
43600
43601
43602
43603
43604
43605
43606
43607
43608
43609
43610
43611
43612
43613
43614
43615
43616
43617
43618
43619
43620
43621
43622
43623
43624
43625
43626
43627
43628
43629
43630
43631
43632
43633
43634
43635
43636
43637
43638
43639
43640
43641
43642
43643
43644
43645
43646
43647
43648
43649
43650
43651
43652
43653
43654
43655
43656
43657
43658
43659
43660
43661
43662
43663
43664
43665
43666
43667
43668
43669
43670
43671
43672
43673
43674
43675
43676
43677
43678
43679
43680
43681
43682
43683
43684
43685
43686
43687
43688
43689
43690
43691
43692
43693
43694
43695
43696
43697
43698
43699
43700
43701
43702
43703
43704
43705
43706
43707
43708
43709
43710
43711
43712
43713
43714
43715
43716
43717
43718
43719
43720
43721
43722
43723
43724
43725
43726
43727
43728
43729
43730
43731
43732
43733
43734
43735
43736
43737
43738
43739
43740
43741
43742
43743
43744
43745
43746
43747
43748
43749
43750
43751
43752
43753
43754
43755
43756
43757
43758
43759
43760
43761
43762
43763
43764
43765
43766
43767
43768
43769
43770
43771
43772
43773
43774
43775
43776
43777
43778
43779
43780
43781
43782
43783
43784
43785
43786
43787
43788
43789
43790
43791
43792
43793
43794
43795
43796
43797
43798
43799
43800
43801
43802
43803
43804
43805
43806
43807
43808
43809
43810
43811
43812
43813
43814
43815
43816
43817
43818
43819
43820
43821
43822
43823
43824
43825
43826
43827
43828
43829
43830
43831
43832
43833
43834
43835
43836
43837
43838
43839
43840
43841
43842
43843
43844
43845
43846
43847
43848
43849
43850
43851
43852
43853
43854
43855
43856
43857
43858
43859
43860
43861
43862
43863
43864
43865
43866
43867
43868
43869
43870
43871
43872
43873
43874
43875
43876
43877
43878
43879
43880
43881
43882
43883
43884
43885
43886
43887
43888
43889
43890
43891
43892
43893
43894
43895
43896
43897
43898
43899
43900
43901
43902